
AWSTemplateFormatVersion : 2010-09-09
Description: Apache Guacamole Server
Parameters:
  Ami:
    Type: String
    Default: ami-43a15f3e
    Description: Please provide an AWS Ubuntu image id
  InstanceTypeParameter:
    Type: String
    Default: t2.medium
  InstanceSubnet:
    Type: String
    Default: subnet-2b976000
  SecurityGroupId:
    Type: String
    Default: sg-58e1fc3d
  InstanceKeyPairParameter:
    Type: String
    Default: TreaEBSLab
    Description: Name of the KeyPair you choose to use to ssh into the box    
  UserName:
    Type: String
    Default: chang.li3@treasury.gov
  Password:
    Type: String
    Default: changeme!!!
  RdpBastion01:
    Type: String
    Default: trlabmgt01.treasury.lab

Resources:
  GuacamoleServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: Ami
      KeyName:
        Ref: InstanceKeyPairParameter
      InstanceType:
        Ref: InstanceTypeParameter
      SecurityGroupIds:
        - !Ref SecurityGroupId
      SubnetId:
        Ref: InstanceSubnet
      Tags:
        -
          Key: Name
          Value: Apache Guacamole Server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          curl -s -L https://raw.githubusercontent.com/changli3/guacamole-aws-cloudformation/master/install.sh | sudo bash -s ${UserName} ${Password} ${RdpBastion01}

Outputs:
  GuacamoleServer:
    Description: The web front URL to view the GuacamoleServer
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - GuacamoleServer
          - PrivateIp
        - '/guacamole'