AWSTemplateFormatVersion : 2010-09-09
Description: Apache Guacamole Server Cluster w/ RDS Auth by chang.li3@treasury.gov
Parameters:
  Ami:
    Type: String
    Description: Latest Ubuntu 16.04 Ami in your AWS Region
    Default: ami-43a15f3e

  AsgMaxSize:
    Type: Number
    Description: The maximum size of ASG
    Default: 4

  AsgMinSize:
    Type: Number
    Description: The minimum size of ASG
    Default: 1

  EmailAlerts:
    Type: String
    Default: cahng.li3@treasury.gov

  InstanceType:
    Type: String
    Default: t2.medium

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to instances

  SubnetID1:
    Type: AWS::EC2::Subnet::Id

  SubnetID2:
    Type: AWS::EC2::Subnet::Id

  VpcId:
    Type: AWS::EC2::VPC::Id
  Sg:
    Type: AWS::EC2::SecurityGroup::Id

  AllowIPs:
    Type: String
    Default: 0.0.0.0/0

  mysqlRootUser:
    Type: String
    Default: mysqlRootUser
  mysqlRootUserPassword:
    Type: String
    Default: mysqlRootUserPassword
  GuacadminUser:
    Type: String
    Default: guacaadmin
  GuacadminPassword:
    Type: String
    Default: guacaadmin

  AllocatedStorage:
    Type: Number
    Description: Allocated Storage for RDS in GB
    Default: 20

  SnapshotOnDelete:
    Description: Create a Snapshot on Delete?
    Type: String
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'

  AutoMinorVersionUpgrade:
    Description: Allow Automatic Minor Version Upgrades?
    Type: String
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'

  BackupRetentionPeriod:
    Description: Enter Backup Retention Period in Days.
    Type: Number
    Default: '1'

  MultiAvailabilityZone:
    Description: Enable Multi Availability Zones?
    Type: String
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'

  ProvisionedIopsValue:
    Description: "(Skip if Not Using Provisioned IOPS) Set Provisioned IOPS 1000-30000."
    Type: Number
    Default: '1000'
    MinValue: '1000'
    MaxValue: '30000'

  RDSInstanceType:
    Description: Select Instance Type.
    Type: String
    Default: db.t2.small
  TcpPort:
    Description: Enter RDS Listening TCP Port number.
    Type: Number
    Default: '3306'


Resources:
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription:
        Fn::Join:
        - ''
        - - 'RDS Subnet Group for '
          - Ref: AWS::StackName
      SubnetIds:
      - Ref: SubnetID1
      - Ref: SubnetID2
      Tags:
      - Key: Name
        Value:
          Ref: AWS::StackName
  DbInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    DependsOn:
    - DbSubnetGroup
    Properties:
      AllocatedStorage:
        Ref: AllocatedStorage
      AllowMajorVersionUpgrade: 'false'
      AutoMinorVersionUpgrade:
        Ref: AutoMinorVersionUpgrade
      BackupRetentionPeriod:
        Ref: BackupRetentionPeriod
      DBInstanceClass:
        Ref: RDSInstanceType
      DBInstanceIdentifier:
        Ref: AWS::StackName
      DBSubnetGroupName:
        Ref: DbSubnetGroup
      Engine: MySQL
      EngineVersion: '5.7'
      MasterUsername:
        Ref: mysqlRootUser
      MasterUserPassword:
        Ref: mysqlRootUserPassword
      MultiAZ:
        Ref: MultiAvailabilityZone
      Port:
        Ref: TcpPort
      PubliclyAccessible: 'false'
      StorageEncrypted: 'false'
      StorageType: gp2
      VPCSecurityGroups:
      - Ref: Sg
      Tags:
      - Key: Name
        Value:
          Ref: AWS::StackName

  AlertsTopic: 
    Type: AWS::SNS::Topic
    Properties: 
      Subscription: 
        - Endpoint: !Ref EmailAlerts
          Protocol: email
      TopicName: 
        Fn::Sub: ${AWS::StackName}-AlertsTopic

  HostRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
            - autoscaling.amazonaws.com
            - rds.amazonaws.com
            - cloudformation.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName:
          Fn::Sub: ${AWS::StackName}-GetCloudformation
        PolicyDocument:
          Statement:
          - Action:
            - cloudformation:DescribeStacks
            - cloudformation:DescribeStackEvents
            - cloudformation:DescribeStackResource
            - cloudformation:DescribeStackResources
            - cloudformation:GetTemplate
            - cloudformation:List*
            Resource: "*"
            Effect: Allow
      - PolicyName:
          Fn::Sub: ${AWS::StackName}-ManageInstances
        PolicyDocument:
          Statement:
          - Action:
            - ec2:*
            Resource: "*"
            Effect: Allow

  HostProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
      - Ref: HostRole

  Asg:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
      - !Ref SubnetID1
      - !Ref SubnetID2
      NotificationConfiguration:
        TopicARN:
          Ref: AlertsTopic
        NotificationTypes:
        - autoscaling:EC2_INSTANCE_LAUNCH
        - autoscaling:EC2_INSTANCE_TERMINATE
        - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
        - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
      HealthCheckGracePeriod: '600'
      HealthCheckType: EC2
      LoadBalancerNames: 
      LaunchConfigurationName:
        Ref: Lc
      MinSize:
        Ref: AsgMinSize
      MaxSize:
        Ref: AsgMaxSize
      DesiredCapacity:
        Ref: AsgMinSize
      LoadBalancerNames:
      - Ref: ElbGuacamole
      Tags:
      - Key: Name
        Value: GuacamoleCluster
        PropagateAtLaunch: true
      - Key: Creator
        Value:
          Ref: KeyName
        PropagateAtLaunch: true
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService:
          Ref: AsgMinSize
        PauseTime: PT5M

  Lc:
    Type: AWS::AutoScaling::LaunchConfiguration
    DependsOn: DbInstance
    Properties:
      ImageId:
        Ref: Ami
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeSize: 30
          VolumeType: gp2
      InstanceType:
        Ref: InstanceType
      IamInstanceProfile:
        Ref: HostProfile
      KeyName:
        Ref: KeyName
      SecurityGroups:
      - Ref: Sg
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #cloud-config
            runcmd:
            - curl -s -L https://raw.githubusercontent.com/changli3/guacamole-aws-cloudformation/master/install-cluster-node.sh | sudo bash -s ${mysqlRootUser} ${mysqlRootUserPassword} ${GuacadminUser} ${GuacadminPassword}  ${DbInstance.Endpoint.Address} ${DbInstance.Endpoint.Port}

  CpuUtilization:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName:
        Ref: Asg
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        TargetValue: 70
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization

  NetworkInAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
      - Ref: AlertsTopic
      MetricName: NetworkIn
      ComparisonOperator: GreaterThanThreshold
      AlarmDescription: High network input traffic during 15 minutes
      Statistic: Average
      Period: '300'
      Dimensions:
      - Value:
          Ref: Asg
        Name: AutoScalingGroupName
      EvaluationPeriods: '3'
      InsufficientDataActions:
      - Ref: AlertsTopic
      Namespace: AWS/EC2
      Threshold: '2400000000'

  RAMAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
      - Ref: AlertsTopic
      MetricName: MemoryUtilization
      ComparisonOperator: GreaterThanThreshold
      AlarmDescription: Memory utilization > 85% during 15 minutes
      Statistic: Average
      Period: '300'
      Dimensions:
      - Value:
          Ref: Asg
        Name: AutoScalingGroupName
      EvaluationPeriods: '3'
      InsufficientDataActions:
      - Ref: AlertsTopic
      Namespace: System/Linux
      Threshold: '85'

  NetworkOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
      - Ref: AlertsTopic
      MetricName: NetworkOut
      ComparisonOperator: GreaterThanThreshold
      AlarmDescription: High network output traffic during 15 minutes
      Statistic: Average
      Period: '300'
      Dimensions:
      - Value:
          Ref: Asg
        Name: AutoScalingGroupName
      EvaluationPeriods: '3'
      InsufficientDataActions:
      - Ref: AlertsTopic
      Namespace: AWS/EC2
      Threshold: '2400000000'

  IOWaitAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
      - Ref: AlertsTopic
      MetricName: IOWait
      ComparisonOperator: GreaterThanThreshold
      AlarmDescription: Alarm if IOWait > 85% for 15 minutes
      Statistic: Average
      Period: '300'
      Dimensions:
      - Value:
          Ref: AWS::StackName
        Name: StackName
      EvaluationPeriods: '3'
      InsufficientDataActions:
      - Ref: AlertsTopic
      Namespace: AWS/EC2
      Threshold: '85'

  StatusAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
      - Ref: AlertsTopic
      MetricName: StatusCheckFailed
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmDescription: Alert if asg has degraded instances
      Statistic: Maximum
      Period: '60'
      Dimensions:
      - Value:
          Ref: Asg
        Name: AutoScalingGroupName
      EvaluationPeriods: '2'
      InsufficientDataActions:
      - Ref: AlertsTopic
      Unit: Count
      Namespace: AWS/EC2
      Threshold: '1'


  ElbGuacamole:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      LoadBalancerName:
        Fn::Sub: ${AWS::StackName}
      Scheme: internal
      Subnets: 
      - !Ref SubnetID1
      - !Ref SubnetID2
      SecurityGroups: [ !Ref Sg ]
      HealthCheck:
        Target:
          Fn::Join:
          - ''
          - - 'HTTP:'
            - '8080'
            - "/guacamole"
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '30'
        Timeout: '5'
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '8080'
        Protocol: TCP
      - LoadBalancerPort: '8080'
        InstancePort: '8080'
        Protocol: TCP


Outputs:
  GuacamoleURL:
    Description: The URL to check the Guacamole Cluster
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - ElbGuacamole
          - DNSName
        - /guacamole
